import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, TrendingDown, Clock, Route } from "lucide-react";

interface OptimizedRouteProps {
  depot: string;
  cities: string[];
}

const OptimizedRoute = ({ depot, cities }: OptimizedRouteProps) => {
  const sortedCities = [...cities];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="card-premium p-6 glow-primary-strong"
    >
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-success/10 flex items-center justify-center">
            <CheckCircle2 className="w-4.5 h-4.5 text-success" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-foreground">AI Optimized Delivery Path</h3>
            <p className="text-[10px] text-muted-foreground">Generated by GAT-RL Engine</p>
          </div>
        </div>
        <div className="flex items-center gap-1 px-2.5 py-1 rounded-full bg-success/10 border border-success/20">
          <Route className="w-3 h-3 text-success" />
          <span className="text-[10px] font-semibold text-success">OPTIMAL</span>
        </div>
      </div>

      <div className="flex items-center gap-1.5 flex-wrap mb-5">
        <motion.span
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.1 }}
          className="px-3.5 py-2 rounded-lg bg-primary/15 border border-primary/30 text-xs font-bold text-primary"
        >
          🏭 {depot}
        </motion.span>
        {sortedCities.map((city, i) => (
          <motion.div
            key={city}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 + i * 0.1 }}
            className="flex items-center gap-1.5"
          >
            <ArrowRight className="w-3.5 h-3.5 text-primary/50" />
            <span className="px-3.5 py-2 rounded-lg bg-secondary border border-border text-xs font-medium text-foreground hover:border-primary/20 transition-colors">
              📦 {city}
            </span>
          </motion.div>
        ))}
        <motion.div
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 + sortedCities.length * 0.1 }}
          className="flex items-center gap-1.5"
        >
          <ArrowRight className="w-3.5 h-3.5 text-primary/50" />
          <span className="px-3.5 py-2 rounded-lg bg-primary/15 border border-primary/30 text-xs font-bold text-primary">
            🏭 {depot}
          </span>
        </motion.div>
      </div>

      <div className="flex gap-6 text-xs text-muted-foreground">
        <div className="flex items-center gap-1.5">
          <Route className="w-3.5 h-3.5 text-primary" />
          Distance: <strong className="text-foreground">{(cities.length * 280 + 120).toLocaleString()} km</strong>
        </div>
        <div className="flex items-center gap-1.5">
          <Clock className="w-3.5 h-3.5 text-info" />
          Time: <strong className="text-foreground">{Math.round(cities.length * 4.5 + 2)}h</strong>
        </div>
        <div className="flex items-center gap-1.5">
          <TrendingDown className="w-3.5 h-3.5 text-success" />
          Spoilage: <strong className="text-success">-31%</strong>
        </div>
      </div>
    </motion.div>
  );
};

export default OptimizedRoute;
